Repository every-ting/back-end_v1, pull requests merged in 2023-05, with the labels that each got.

#15 Feature/#3 searching user
  src/main/java/com/ting/ting/controller/BlindDateController.java
  src/main/java/com/ting/ting/domain/User.java
  src/main/java/com/ting/ting/domain/constant/Gender.java
  src/main/java/com/ting/ting/domain/constant/MBTI.java
  src/main/java/com/ting/ting/dto/BlindUsersInfoResponse.java
  src/main/java/com/ting/ting/repository/UserRepository.java
  src/main/java/com/ting/ting/service/UserService.java
  src/main/resources/application.yml
Labels: enhancement

#23 [소개팅] 메인 페이지
  src/main/java/com/ting/ting/controller/BlindDateController.java
  src/main/java/com/ting/ting/domain/BlindRequest.java
  src/main/java/com/ting/ting/domain/User.java
  src/main/java/com/ting/ting/domain/constant/MBTI.java
  src/main/java/com/ting/ting/domain/constant/RequestStatus.java
  src/main/java/com/ting/ting/dto/request/SendBlindRequest.java
  src/main/java/com/ting/ting/dto/response/BlindUsersInfoResponse.java
  src/main/java/com/ting/ting/exception/UserException.java
  src/main/java/com/ting/ting/repository/BlindRequestRepository.java
  src/main/java/com/ting/ting/repository/UserRepository.java
  src/main/java/com/ting/ting/service/BlindRequestService.java
  src/main/java/com/ting/ting/service/UserService.java
  src/main/resources/data.sql
Labels: enhancement

#28 Swagger 연동
  build.gradle
  src/main/java/com/ting/ting/configuration/SwaggerConfig.java
  src/main/java/com/ting/ting/controller/BlindDateController.java
  src/main/java/com/ting/ting/controller/GroupController.java
  src/main/java/com/ting/ting/dto/request/GroupRequest.java
  src/main/java/com/ting/ting/dto/request/SendBlindRequest.java
  src/main/java/com/ting/ting/repository/BlindRequestRepository.java
  src/main/java/com/ting/ting/service/BlindRequestService.java
  src/main/java/com/ting/ting/service/UserService.java
  src/main/resources/application.yml
Labels: documentation, enhancement

#48 [리팩토링] test를 위한 Fixture 도입
  src/main/java/com/ting/ting/service/GroupService.java
  src/test/java/com/ting/ting/fixture/GroupFixture.java
  src/test/java/com/ting/ting/fixture/UserFixture.java
  src/test/java/com/ting/ting/service/GroupServiceTest.java
Labels: enhancement, Revise

#49 Gender 처리 로직 변경
  src/main/java/com/ting/ting/domain/Group.java
  src/main/java/com/ting/ting/domain/User.java
  src/main/java/com/ting/ting/domain/constant/Gender.java
  src/main/java/com/ting/ting/service/UserService.java
  src/main/resources/data.sql
  src/test/java/com/ting/ting/service/GroupServiceTest.java
Labels: Revise

#44 [custom exception] 구현
  src/main/java/com/ting/ting/controller/BlindDateController.java
  src/main/java/com/ting/ting/controller/GlobalControllerAdvice.java
  src/main/java/com/ting/ting/exception/ErrorCode.java
  src/main/java/com/ting/ting/exception/TingApplicationException.java
  src/main/java/com/ting/ting/exception/UserException.java
  src/main/java/com/ting/ting/service/BlindRequestService.java
  src/main/java/com/ting/ting/service/ServiceType.java
  src/main/java/com/ting/ting/service/UserService.java
Labels: enhancement

#51 Custom Response 구현
  src/main/java/com/ting/ting/AppConfig.java
  src/main/java/com/ting/ting/controller/AbstractController.java
  src/main/java/com/ting/ting/controller/BlindDateController.java
  src/main/java/com/ting/ting/controller/BlindDateControllerImpl.java
  src/main/java/com/ting/ting/controller/GlobalControllerAdvice.java
  src/main/java/com/ting/ting/controller/GroupController.java
  src/main/java/com/ting/ting/controller/GroupControllerImpl.java
  src/main/java/com/ting/ting/domain/Group.java
  src/main/java/com/ting/ting/domain/GroupMemberRequest.java
  src/main/java/com/ting/ting/dto/response/Response.java
  src/main/java/com/ting/ting/dto/response/ResultObject.java
  src/main/java/com/ting/ting/exception/ErrorCode.java
  src/main/java/com/ting/ting/exception/GlobalControllerAdvice.java
  src/main/java/com/ting/ting/exception/ServiceType.java
  src/main/java/com/ting/ting/exception/TingApplicationException.java
  src/main/java/com/ting/ting/service/AbstractService.java
  src/main/java/com/ting/ting/service/BlindRequestService.java
  src/main/java/com/ting/ting/service/BlindRequestServiceImpl.java
  src/main/java/com/ting/ting/service/GroupService.java
  src/main/java/com/ting/ting/service/GroupServiceImpl.java
  src/main/java/com/ting/ting/service/UserService.java
  src/main/java/com/ting/ting/service/UserServiceImpl.java
  src/main/resources/application.yml
  src/main/resources/data.sql
  src/test/java/com/ting/ting/fixture/GroupFixture.java
  src/test/java/com/ting/ting/fixture/UserFixture.java
  src/test/java/com/ting/ting/service/GroupServiceTest.java
Labels: enhancement, Revise

#55 ResponseDto, RequestDto 아닌 Dto 제거
  src/main/java/com/ting/ting/controller/GroupController.java
  src/main/java/com/ting/ting/controller/GroupControllerImpl.java
  src/main/java/com/ting/ting/dto/GroupDto.java
  src/main/java/com/ting/ting/dto/UserDto.java
  src/main/java/com/ting/ting/dto/request/GroupRequest.java
  src/main/java/com/ting/ting/dto/response/GroupResponse.java
  src/main/java/com/ting/ting/dto/response/UserResponse.java
  src/main/java/com/ting/ting/service/GroupService.java
  src/main/java/com/ting/ting/service/GroupServiceImpl.java
  src/test/java/com/ting/ting/fixture/GroupFixture.java
  src/test/java/com/ting/ting/service/GroupServiceTest.java
Labels: enhancement, Revise

#59 [소개팅] 요청 관련 로직 처리 완료
  src/main/java/com/ting/ting/configuration/AppConfig.java
  src/main/java/com/ting/ting/controller/BlindDateController.java
  src/main/java/com/ting/ting/controller/BlindDateControllerImpl.java
  src/main/java/com/ting/ting/domain/BlindRequest.java
  src/main/java/com/ting/ting/dto/response/BlindDateResponse.java
  src/main/java/com/ting/ting/exception/ErrorCode.java
  src/main/java/com/ting/ting/repository/BlindRequestRepository.java
  src/main/java/com/ting/ting/service/BlindRequestService.java
  src/main/java/com/ting/ting/service/BlindRequestServiceImpl.java
  src/main/java/com/ting/ting/service/UserService.java
  src/main/java/com/ting/ting/service/UserServiceImpl.java
  src/main/resources/data.sql
Labels: enhancement

#70 [과팅] 팀장 권한 기능 구현
  src/main/java/com/ting/ting/configuration/AppConfig.java
  src/main/java/com/ting/ting/controller/GroupController.java
  src/main/java/com/ting/ting/controller/GroupControllerImpl.java
  src/main/java/com/ting/ting/domain/Group.java
  src/main/java/com/ting/ting/domain/GroupDate.java
  src/main/java/com/ting/ting/domain/GroupDateRequest.java
  src/main/java/com/ting/ting/domain/GroupMember.java
  src/main/java/com/ting/ting/domain/GroupMemberRequest.java
  src/main/java/com/ting/ting/domain/constant/MemberRole.java
  src/main/java/com/ting/ting/domain/constant/MemberStatus.java
  src/main/java/com/ting/ting/dto/request/GroupRequest.java
  src/main/java/com/ting/ting/dto/response/GroupDateRequestResponse.java
  src/main/java/com/ting/ting/dto/response/GroupDateResponse.java
  src/main/java/com/ting/ting/dto/response/GroupMemberRequestResponse.java
  src/main/java/com/ting/ting/dto/response/GroupMemberResponse.java
  src/main/java/com/ting/ting/dto/response/GroupResponse.java
  src/main/java/com/ting/ting/dto/response/UserResponse.java
  src/main/java/com/ting/ting/exception/ErrorCode.java
  src/main/java/com/ting/ting/repository/GroupDateRepository.java
  src/main/java/com/ting/ting/repository/GroupDateRequestRepository.java
  src/main/java/com/ting/ting/repository/GroupMemberRepository.java
  src/main/java/com/ting/ting/repository/GroupMemberRequestRepository.java
  src/main/java/com/ting/ting/repository/GroupRepository.java
  src/main/java/com/ting/ting/service/GroupService.java
  src/main/java/com/ting/ting/service/GroupServiceImpl.java
  src/main/resources/data.sql
  src/test/java/com/ting/ting/fixture/GroupFixture.java
  src/test/java/com/ting/ting/fixture/UserFixture.java
  src/test/java/com/ting/ting/service/GroupServiceTest.java
Labels: enhancement, Revise

#74 [과팅] 내가 속한 팀 나오기 기능 구현
  src/main/java/com/ting/ting/controller/GroupController.java
  src/main/java/com/ting/ting/controller/GroupControllerImpl.java
  src/main/java/com/ting/ting/exception/ErrorCode.java
  src/main/java/com/ting/ting/repository/GroupMemberRepository.java
  src/main/java/com/ting/ting/service/GroupService.java
  src/main/java/com/ting/ting/service/GroupServiceImpl.java
  src/test/java/com/ting/ting/fixture/GroupFixture.java
  src/test/java/com/ting/ting/fixture/UserFixture.java
  src/test/java/com/ting/ting/service/GroupServiceTest.java
Labels: enhancement, Revise

#80 [소개팅] 요청 및 조회 수정
  src/main/java/com/ting/ting/controller/BlindDateControllerImpl.java
  src/main/java/com/ting/ting/exception/ErrorCode.java
  src/main/java/com/ting/ting/repository/BlindRequestRepository.java
  src/main/java/com/ting/ting/repository/UserRepository.java
  src/main/java/com/ting/ting/service/BlindRequestServiceImpl.java
Labels: Revise

#82 [헤로쿠] 배포
  Procfile
  src/main/java/com/ting/ting/configuration/WebConfig.java
  system.properties
Labels: enhancement

#81 [과팅] 같은 성별의 팀 & 내가 속하지 않은 팀 조회 기능 구현
  src/main/java/com/ting/ting/controller/AdminController.java
  src/main/java/com/ting/ting/controller/AdminControllerImpl.java
  src/main/java/com/ting/ting/controller/GroupController.java
  src/main/java/com/ting/ting/controller/GroupControllerImpl.java
  src/main/java/com/ting/ting/domain/Group.java
  src/main/java/com/ting/ting/domain/custom/SuggestedGroupWithRequestStatus.java
  src/main/java/com/ting/ting/dto/response/GroupResponse.java
  src/main/java/com/ting/ting/dto/response/GroupWithRequestStatusResponse.java
  src/main/java/com/ting/ting/exception/ServiceType.java
  src/main/java/com/ting/ting/repository/GroupRepository.java
  src/main/java/com/ting/ting/service/GroupService.java
  src/main/java/com/ting/ting/service/GroupServiceImpl.java
  src/main/resources/data.sql
  src/test/java/com/ting/ting/service/GroupServiceTest.java
Labels: enhancement

#89 [소개팅] 소개팅 조회 로직, 소개팅 성공시 저장 로직 추가
  src/main/java/com/ting/ting/configuration/AppConfig.java
  src/main/java/com/ting/ting/controller/BlindDateController.java
  src/main/java/com/ting/ting/controller/BlindDateControllerImpl.java
  src/main/java/com/ting/ting/domain/BlindDate.java
  src/main/java/com/ting/ting/domain/custom/BlindUserWithRequestStatus.java
  src/main/java/com/ting/ting/dto/response/BlindUserWithRequestStatusResponse.java
  src/main/java/com/ting/ting/exception/ErrorCode.java
  src/main/java/com/ting/ting/repository/BlindDateRepository.java
  src/main/java/com/ting/ting/repository/BlindRequestRepository.java
  src/main/java/com/ting/ting/repository/UserRepository.java
  src/main/java/com/ting/ting/service/BlindService.java
  src/main/java/com/ting/ting/service/BlindServiceImpl.java
Labels: enhancement

#93 [과팅] Group Entity의 numOfMembers 필드명을 memberSizeLimit 으로 변경
  src/main/java/com/ting/ting/domain/Group.java
  src/main/java/com/ting/ting/domain/custom/SuggestedGroupWithRequestStatus.java
  src/main/java/com/ting/ting/dto/request/GroupRequest.java
  src/main/java/com/ting/ting/dto/response/GroupResponse.java
  src/main/java/com/ting/ting/dto/response/GroupWithRequestStatusResponse.java
  src/main/java/com/ting/ting/repository/GroupRepository.java
  src/main/java/com/ting/ting/service/GroupServiceImpl.java
  src/main/resources/data.sql
  src/test/java/com/ting/ting/service/GroupServiceTest.java
Labels: Revise

#96 Feature/#90 blind change search
  src/main/java/com/ting/ting/controller/BlindDateController.java
  src/main/java/com/ting/ting/controller/BlindDateControllerImpl.java
  src/main/java/com/ting/ting/dto/response/BlindRequestWithFromAndToResponse.java
  src/main/java/com/ting/ting/service/BlindService.java
  src/main/java/com/ting/ting/service/BlindServiceImpl.java
Labels: enhancement, Revise

#97 [소개팅] 조회, 수락 및 거절 로직 변경
  src/main/java/com/ting/ting/controller/BlindDateController.java
  src/main/java/com/ting/ting/controller/BlindDateControllerImpl.java
  src/main/java/com/ting/ting/domain/BlindLikes.java
  src/main/java/com/ting/ting/dto/response/BlindRequestWithFromAndToResponse.java
  src/main/java/com/ting/ting/service/BlindService.java
  src/main/java/com/ting/ting/service/BlindServiceImpl.java
Labels: enhancement, Revise

#91 [과팅] [팀장] 팀 초대하기
  build.gradle
  src/main/java/com/ting/ting/configuration/AppConfig.java
  src/main/java/com/ting/ting/configuration/S3Config.java
  src/main/java/com/ting/ting/controller/GroupController.java
  src/main/java/com/ting/ting/controller/GroupControllerImpl.java
  src/main/java/com/ting/ting/domain/Group.java
  src/main/java/com/ting/ting/domain/GroupInvitation.java
  src/main/java/com/ting/ting/domain/GroupMember.java
  src/main/java/com/ting/ting/domain/custom/SuggestedGroupWithRequestStatus.java
  src/main/java/com/ting/ting/dto/request/GroupRequest.java
  src/main/java/com/ting/ting/dto/response/GroupInvitationResponse.java
  src/main/java/com/ting/ting/dto/response/GroupResponse.java
  src/main/java/com/ting/ting/dto/response/GroupWithRequestStatusResponse.java
  src/main/java/com/ting/ting/exception/ErrorCode.java
  src/main/java/com/ting/ting/repository/GroupInvitationRepository.java
  src/main/java/com/ting/ting/repository/GroupMemberRepository.java
  src/main/java/com/ting/ting/repository/GroupRepository.java
  src/main/java/com/ting/ting/service/GroupService.java
  src/main/java/com/ting/ting/service/GroupServiceImpl.java
  src/main/java/com/ting/ting/util/QRCodeGenerator.java
  src/main/java/com/ting/ting/util/S3StorageManager.java
  src/main/resources/application.yml
  src/main/resources/data.sql
  src/test/java/com/ting/ting/TingApplicationTests.java
  src/test/java/com/ting/ting/service/GroupServiceTest.java
  src/test/resources/test.properties
Labels: enhancement, Revise

#99 [과팅] [팀장] 팀 초대 취소
  src/main/java/com/ting/ting/controller/GroupController.java
  src/main/java/com/ting/ting/controller/GroupControllerImpl.java
  src/main/java/com/ting/ting/domain/GroupInvitation.java
  src/main/java/com/ting/ting/dto/response/GroupInvitationResponse.java
  src/main/java/com/ting/ting/repository/GroupInvitationRepository.java
  src/main/java/com/ting/ting/service/GroupService.java
  src/main/java/com/ting/ting/service/GroupServiceImpl.java
  src/main/java/com/ting/ting/util/S3StorageManager.java
  src/test/java/com/ting/ting/service/GroupServiceTest.java
Labels: enhancement

#110 Auditing Field 추가
  src/main/java/com/ting/ting/TingApplication.java
  src/main/java/com/ting/ting/domain/AuditingFields.java
  src/main/java/com/ting/ting/domain/BlindDate.java
  src/main/java/com/ting/ting/domain/BlindLikes.java
  src/main/java/com/ting/ting/domain/BlindRequest.java
  src/main/java/com/ting/ting/domain/Group.java
  src/main/java/com/ting/ting/domain/GroupDate.java
  src/main/java/com/ting/ting/domain/GroupDateRequest.java
  src/main/java/com/ting/ting/domain/GroupInvitation.java
  src/main/java/com/ting/ting/domain/GroupMember.java
  src/main/java/com/ting/ting/domain/GroupMemberRequest.java
  src/main/java/com/ting/ting/domain/User.java
  src/main/resources/data.sql
Labels: enhancement

#114 [과팅] QR 코드 초대 기능 revert
  src/main/java/com/ting/ting/configuration/AppConfig.java
  src/main/java/com/ting/ting/controller/GroupController.java
  src/main/java/com/ting/ting/controller/GroupControllerImpl.java
  src/main/java/com/ting/ting/domain/GroupInvitation.java
  src/main/java/com/ting/ting/domain/GroupMember.java
  src/main/java/com/ting/ting/domain/constant/MemberStatus.java
  src/main/java/com/ting/ting/dto/response/GroupInvitationResponse.java
  src/main/java/com/ting/ting/dto/response/GroupMemberResponse.java
  src/main/java/com/ting/ting/repository/GroupInvitationRepository.java
  src/main/java/com/ting/ting/repository/GroupMemberRepository.java
  src/main/java/com/ting/ting/service/GroupService.java
  src/main/java/com/ting/ting/service/GroupServiceImpl.java
  src/main/resources/application.yml
  src/main/resources/data.sql
  src/test/java/com/ting/ting/service/GroupServiceTest.java
Labels: enhancement, Revise

#116 [과팅] 같은 성별의 팀 찜 기능 구현
  src/main/java/com/ting/ting/configuration/AppConfig.java
  src/main/java/com/ting/ting/controller/GroupController.java
  src/main/java/com/ting/ting/controller/GroupControllerImpl.java
  src/main/java/com/ting/ting/domain/GroupLikeToDate.java
  src/main/java/com/ting/ting/domain/GroupLikeToJoin.java
  src/main/java/com/ting/ting/domain/custom/GroupWithMemberCount.java
  src/main/java/com/ting/ting/domain/custom/GroupWithMemberCountAndRole.java
  src/main/java/com/ting/ting/dto/response/GroupResponse.java
  src/main/java/com/ting/ting/dto/response/GroupWithLikeStatusResponse.java
  src/main/java/com/ting/ting/dto/response/GroupWithRequestStatusResponse.java
  src/main/java/com/ting/ting/dto/response/GroupWithStatusResponse.java
  src/main/java/com/ting/ting/repository/GroupLikeToJoinRepository.java
  src/main/java/com/ting/ting/repository/GroupMemberRepository.java
  src/main/java/com/ting/ting/repository/GroupMemberRequestRepository.java
  src/main/java/com/ting/ting/repository/GroupRepository.java
  src/main/java/com/ting/ting/service/GroupLikeService.java
  src/main/java/com/ting/ting/service/GroupLikeServiceImpl.java
  src/main/java/com/ting/ting/service/GroupService.java
  src/main/java/com/ting/ting/service/GroupServiceImpl.java
  src/main/resources/data.sql
  src/test/java/com/ting/ting/service/GorupLikeServiceTest.java
  src/test/java/com/ting/ting/service/GroupServiceTest.java
Labels: enhancement

#123 [과팅] 다른 성별의 팀 조회 - 멤버들의 평균나이, 멤버들의 전공 추가
  src/main/java/com/ting/ting/controller/GroupController.java
  src/main/java/com/ting/ting/controller/GroupControllerImpl.java
  src/main/java/com/ting/ting/dto/response/DateableGroupResponse.java
  src/main/java/com/ting/ting/dto/response/GroupResponse.java
  src/main/java/com/ting/ting/repository/GroupLikeToDateRepository.java
  src/main/java/com/ting/ting/repository/GroupRepository.java
  src/main/java/com/ting/ting/service/GroupService.java
  src/main/java/com/ting/ting/service/GroupServiceImpl.java
  src/main/resources/data.sql
  src/test/java/com/ting/ting/service/GroupServiceTest.java
Labels: enhancement, Revise

#124 [소개팅] 찜 서비스 분리
  src/main/java/com/ting/ting/configuration/AppConfig.java
  src/main/java/com/ting/ting/controller/BlindDateControllerImpl.java
  src/main/java/com/ting/ting/service/BlindLikeService.java
  src/main/java/com/ting/ting/service/BlindLikeServiceImpl.java
  src/main/java/com/ting/ting/service/BlindService.java
  src/main/java/com/ting/ting/service/BlindServiceImpl.java
Labels: Revise

#128 [과팅] 유저 기준 - 찜한 목록 조회 기능 구현
  src/main/java/com/ting/ting/configuration/AppConfig.java
  src/main/java/com/ting/ting/controller/GroupController.java
  src/main/java/com/ting/ting/controller/GroupControllerImpl.java
  src/main/java/com/ting/ting/dto/response/JoinableGroupResponse.java
  src/main/java/com/ting/ting/repository/GroupLikeToJoinRepository.java
  src/main/java/com/ting/ting/repository/GroupMemberRequestRepository.java
  src/main/java/com/ting/ting/repository/GroupRepository.java
  src/main/java/com/ting/ting/service/GroupLikeService.java
  src/main/java/com/ting/ting/service/GroupLikeServiceImpl.java
  src/main/java/com/ting/ting/service/GroupService.java
  src/main/java/com/ting/ting/service/GroupServiceImpl.java
  src/main/resources/data.sql
  src/test/java/com/ting/ting/service/GroupServiceLikeTest.java
  src/test/java/com/ting/ting/service/GroupServiceTest.java
Labels: enhancement
